### ISSUE TITLE
[14567] 선수과목

### ISSUE THREAD

**Issue by ziiyouth** [Dudadakung/AlgoGenius#103]
## 🎈 문제 내용 및 링크
[[14567] 선수과목](https://www.acmicpc.net/problem/14567)
<img width="1185" alt="image" src="https://github.com/Dudadakung/AlgoGenius/assets/101448999/bd859958-ea17-4b30-88ff-1f2aeb754c71">

## 🤔 문제 선정 동기
강어진 번호는 5736

**Comment by Ginieee** [comment]
_010-xxxx-xxxx_
