### ISSUE TITLE
[2573] 빙산

### ISSUE THREAD

**Issue by OJOJIN** [Dudadakung/AlgoGenius#23]
## 🎈 문제 내용 및 링크
[문제링크](https://www.acmicpc.net/problem/2573)

## 🤔 문제 선정 동기
빙하를 지키고싶어서

**Comment by ziiyouth** [comment]
빙하 지키기 멋져요 🧊👍

**Comment by kdhhuns2000** [comment]
분명 내꺼 골라주고 똑같은거 풀자고 했는데..
